### ISSUE TITLE
跟我的想法一模一样 可以看一下我的方案

### ISSUE THREAD

**Issue by fangkyi03** [TalkingData/rxloop#1]
https://github.com/fangkyi03/dvajs
早期我通过修改dva源码就实现了这个在model里面直接使用rxjs的方法
不过因为用法太过复杂 在一些大型场景下面使用方便 但是在一些小场景里面使用就异常麻烦 所以换成了我自己写的一套异步解决方案 

有机会的话 希望能一起互相交流一下 QQ:469373256

**Comment by wxnet2013** [comment]
理念上都是类似的，再比如 rematch，都是对 redux + async middleware 的上层封装。

但 rxloop 是反过来的，在 rxjs 擅长的部分基础上，增加了同步单向数据流的规范，而rxjs 自身很容易做状态管理、处理异步等副作用代码。

所以大家会发现 rxloop/core  的代码，仅有 100 行左右，算的上是超轻量级了。
